### ISSUE TITLE
Busca de arquivo com lentidão

### ISSUE THREAD

**Issue by Matrix2100** [digitalse-bomb/back#15]
Remover campo de bytes e texto da query no banco de dados

**Comment by Matrix2100** [comment]
_07-15 11:43:34 WARN  o.h.e.j.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42703_
_07-15 11:43:34 ERROR o.h.e.j.spi.SqlExceptionHelper -_ **A nome da coluna dados não foi encontrado neste ResultSet.**
_org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute query; SQL [SELECT id, nome, ocr, status, mime, tamanho, criado, atualizado FROM arquivos WHERE id = ?]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query_

**Comment by raiomarco** [comment]
> Ao não retornar alguns campos do DB pela query, gera-se exceção.
> 
> _07-15 11:43:34 WARN o.h.e.j.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42703_
> _07-15 11:43:34 ERROR o.h.e.j.spi.SqlExceptionHelper -_ **A nome da coluna dados não foi encontrado neste ResultSet.**
> _org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute query; SQL [SELECT id, nome, ocr, status, mime, tamanho, criado, atualizado FROM arquivos WHERE id = ?]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query_

Você ta tentando acessar a coluna sem ela ter vindo nos resultados (por exemplo, naquela filtragem pra tirar os dados) não?

**Comment by Matrix2100** [comment]
> > Ao não retornar alguns campos do DB pela query, gera-se exceção.
> > _07-15 11:43:34 WARN o.h.e.j.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42703_
> > _07-15 11:43:34 ERROR o.h.e.j.spi.SqlExceptionHelper -_ **A nome da coluna dados não foi encontrado neste ResultSet.**
> > _org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute query; SQL [SELECT id, nome, ocr, status, mime, tamanho, criado, atualizado FROM arquivos WHERE id = ?]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query_
> 
> Você ta tentando acessar a coluna sem ela ter vindo nos resultados (por exemplo, naquela filtragem pra tirar os dados) não?

Na verdade foi aqueles erros do JPQL e do construtor... ainda ta dando erro mas não é mais a query então vou colocar um commit com parte das correções pra você trabalhar em cima disso

**Comment by Matrix2100** [comment]
Agora está ocorrendo erro na conversão do tipo: 

_`org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.Object[]] to type [com.digitalse.cbm.back.entities.Arquivo] for value '{28, testesback.jpg, false, salada, image/jpeg, 20053, 2021-07-15 11:50:05.64, 2021-07-15 11:50:05.64}'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.Long] to type [com.digitalse.cbm.back.entities.Arquivo]`_

**Comment by raiomarco** [comment]
Adiado para a Entrega 3 devido aos problemas e complexidade

**Comment by raiomarco** [comment]
O #41 deve ter resolvido esse problema, favor verificar e fechar esse issue caso aplicável

**Comment by Matrix2100** [comment]
A issue #41 junto com as correções e refatorações da issue #44 resolveram os problemas de lentidão
